[build]
    publish = "demo/netlify/dist/"
    command = "npm run build"
[functions]
    directory = "functions/netlify"
    external_node_modules = ["pnapi", "uglify-js", "@swc/core"]
    included_files = ["functions/assets/**"]
